### ISSUE TITLE
Help is not working

### ISSUE THREAD

**Issue by SHU-red** [valsorym/.del.vim-colorizer#1]
Sorry i did not want to annoy you but im trying to use your colorizer-plugin.
If i use `:h Colorizer` (as described in the readme on github) i get "no Help for Colorizer"
After using` :helpgrep Colorizer` also nothing is found

The only thing im trying to achieve is, that Colorizer is always on for every Buffer
Right now i always have to type in `:ColorToggle `for every buffer

I could also not manage to get
`au BufEnter ...`
to work to always execute the `ColorToggle`

**Comment by valsorym** [comment]
Hello!

It's a fork of `https://github.com/chrisbra/colorizer` - it's not my project. 

I'm forking some packages to make sure my vim config file will be correct built. I.e. https://github.com/valsorym/vimrc

I am using `chrisbra/colorizer` in my configurations like:

```
" Install colorizer
Plugin 'valsorym/chrisbra-colorizer', {'name': 'colorizer'} " 'chrisbra/colorizer'

...
" Key mapping.
nmap <A-i> :ColorToggle<CR>
```

And it works on `Alt+i` keypress.

P.s. I mark some repositories as `.del` - for further deletion.
